name: docker-publish

# Ce job se déclenche uniquement si la build sur main a réussi
on:
  workflow_run:
    workflows: [ "build-test" ]     # nom du workflow CI existant (ci.yml)
    types: [ completed ]
    branches: [ main ]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push de l’image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kouumss/pulseepr-api:latest   # <username>/<repository>:tag
